<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>V12.Pak</AssemblyName>
    <RootNamespace>V12.Pak</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\V12\V12.csproj" />
    <ProjectReference Include="..\V12.Bindings\V12.Bindings.csproj" />
  </ItemGroup>

</Project>
