using System.Text.Json;

namespace V12.Pak
{
    /// <summary>
    /// Builds a <c>.v12pak</c> from a directory of game content. The directory
    /// layout mirrors the archive layout:
    ///
    /// <code>
    /// input/
    ///   manifest.json            (optional — regenerated when absent)
    ///     worlds/{World}/world.xml
    ///     worlds/{World}/templates/*.xml
    ///     assets/**                (textures, meshes, scripts, ...)
    ///     paks/*.dll
    ///     scripts/*.ct             (Contract gamepack entrypoints)
    /// </code>
    ///
    /// When no manifest.json is present, one is generated by scanning the
    /// directory: worlds/ subdirectories that contain a world.xml (or main.xml)
    /// become world entries, files under assets/ become asset-map entries, files
    /// under paks/ become the pak DLL list, and files under scripts/ become the
    /// Contract script list.
    /// </summary>
    public static class V12PakBuilder
    {
        public static void Build(string inputDirectory, string outputPath)
        {
            if (!Directory.Exists(inputDirectory))
                throw new DirectoryNotFoundException($"Input directory not found: {inputDirectory}");

            var manifest = ReadOrBuildManifest(inputDirectory);

            using var writer = new V12PakWriter(outputPath);
            writer.WriteManifest(manifest);
            WriteAllFiles(writer, inputDirectory);
        }

        private static V12PakManifest ReadOrBuildManifest(string inputDirectory)
        {
            string manifestPath = Path.Combine(inputDirectory, "manifest.json");
            if (File.Exists(manifestPath))
            {
                using var stream = File.OpenRead(manifestPath);
                return JsonSerializer.Deserialize<V12PakManifest>(stream,
                           new JsonSerializerOptions { PropertyNameCaseInsensitive = true })
                       ?? new V12PakManifest();
            }

            var manifest = new V12PakManifest { Version = 1, Engine = "v12" };

            string worldsDir = Path.Combine(inputDirectory, "worlds");
            if (Directory.Exists(worldsDir))
            {
                foreach (var worldDir in Directory.GetDirectories(worldsDir))
                {
                    string name = Path.GetFileName(worldDir);
                    string entry = null!;
                    foreach (var candidate in new[] { "world.xml", "main.xml" })
                    {
                        if (File.Exists(Path.Combine(worldDir, candidate)))
                        {
                            entry = $"worlds/{name}/{candidate}";
                            break;
                        }
                    }
                    if (entry == null) continue;

                    string templatesDir = Path.Combine(worldDir, "templates");
                    manifest.Worlds.Add(new V12PakWorldEntry
                    {
                        Name = name,
                        Entry = entry,
                        TemplatesDir = Directory.Exists(templatesDir) ? $"worlds/{name}/templates/" : ""
                    });
                }
            }

            string assetsDir = Path.Combine(inputDirectory, "assets");
            if (Directory.Exists(assetsDir))
            {
                foreach (var file in Directory.EnumerateFiles(assetsDir, "*", SearchOption.AllDirectories))
                {
                    string relative = Path.GetRelativePath(assetsDir, file).Replace('\\', '/');
                    manifest.Assets[relative] = $"assets/{relative}";
                }
            }

            string paksDir = Path.Combine(inputDirectory, "paks");
            if (Directory.Exists(paksDir))
            {
                foreach (var file in Directory.EnumerateFiles(paksDir, "*.dll", SearchOption.AllDirectories))
                {
                    manifest.Paks.Add(Path.GetRelativePath(inputDirectory, file).Replace('\\', '/'));
                }
            }

            string scriptsDir = Path.Combine(inputDirectory, "scripts");
            if (Directory.Exists(scriptsDir))
            {
                foreach (var pattern in new[] { "*.ct", "*.orbt", "*.oil" })
                    foreach (var file in Directory.EnumerateFiles(scriptsDir, pattern, SearchOption.AllDirectories))
                    {
                        string relative = Path.GetRelativePath(inputDirectory, file).Replace('\\', '/');
                        if (!manifest.Scripts.Contains(relative))
                            manifest.Scripts.Add(relative);
                    }
            }

            return manifest;
        }

        private static void WriteAllFiles(V12PakWriter writer, string inputDirectory)
        {
            foreach (var file in Directory.EnumerateFiles(inputDirectory, "*", SearchOption.AllDirectories))
            {
                string relative = Path.GetRelativePath(inputDirectory, file).Replace('\\', '/');
                if (string.Equals(relative, "manifest.json", StringComparison.OrdinalIgnoreCase)) continue;
                writer.AddFile(relative, file);
            }
        }
    }
}
